-- 20260719140000_species_matrix.sql
-- Expanded species list + state_species mapping, from the reviewed state x
-- species matrix. Generated by scripts/gen_state_species.py - do not hand-edit;
-- re-run the generator to change.

alter table public.species add column if not exists category text;

-- Species (upsert; existing deer/elk/bear/duck keep their ids, gain category) --
insert into public.species (key, name, category, sort_order) values
  ('deer','Deer','big_game',1),
  ('elk','Elk','big_game',2),
  ('moose','Moose','big_game',3),
  ('pronghorn','Pronghorn','big_game',4),
  ('caribou','Caribou','big_game',5),
  ('bison','Bison','big_game',6),
  ('bighorn-sheep','Bighorn sheep','big_game',7),
  ('dall-sheep','Dall sheep','big_game',8),
  ('mountain-goat','Mountain goat','big_game',9),
  ('muskox','Muskox','big_game',10),
  ('bear','Black bear','big_game',11),
  ('brown-bear','Brown/grizzly bear','big_game',12),
  ('mountain-lion','Mountain lion','big_game',13),
  ('javelina','Javelina','big_game',14),
  ('wild-hog','Wild hog','big_game',15),
  ('turkey','Wild turkey','turkey',16),
  ('duck','Ducks','waterfowl',17),
  ('goose','Geese','waterfowl',18),
  ('dove','Mourning dove','waterfowl',19),
  ('band-tailed-pigeon','Band-tailed pigeon','waterfowl',20),
  ('sandhill-crane','Sandhill crane','waterfowl',21),
  ('woodcock','Woodcock','waterfowl',22),
  ('snipe','Snipe','waterfowl',23),
  ('pheasant','Ring-necked pheasant','upland',24),
  ('bobwhite','Bobwhite quail','upland',25),
  ('western-quail','Western quail','upland',26),
  ('ruffed-grouse','Ruffed grouse','upland',27),
  ('spruce-grouse','Spruce grouse','upland',28),
  ('sharptail-grouse','Sharp-tailed grouse','upland',29),
  ('sage-grouse','Sage grouse','upland',30),
  ('prairie-chicken','Prairie chicken','upland',31),
  ('chukar','Chukar','upland',32),
  ('gray-partridge','Gray partridge','upland',33),
  ('ptarmigan','Ptarmigan','upland',34),
  ('rabbit','Cottontail rabbit','small_game',35),
  ('snowshoe-hare','Snowshoe hare','small_game',36),
  ('squirrel','Squirrel','small_game',37),
  ('coyote','Coyote','furbearer',38),
  ('bobcat','Bobcat','furbearer',39),
  ('fox','Fox','furbearer',40),
  ('raccoon','Raccoon','furbearer',41),
  ('fisher','Fisher','furbearer',42),
  ('marten','Marten','furbearer',43),
  ('nutria','Nutria','furbearer',44),
  ('ringtail','Ringtail','furbearer',45),
  ('wolf','Gray wolf','furbearer',46),
  ('wolverine','Wolverine','furbearer',47),
  ('alligator','American alligator','other',48),
  ('crow','Crow','other',49)
on conflict (key) do update set name = excluded.name, category = excluded.category, sort_order = excluded.sort_order;

-- state_species mapping (which species are huntable in which state) --
create table if not exists public.state_species (
  state_id   uuid not null references public.states(id) on delete cascade,
  species_id uuid not null references public.species(id) on delete cascade,
  primary key (state_id, species_id)
);
alter table public.state_species enable row level security;
drop policy if exists state_species_public_read on public.state_species;
create policy state_species_public_read on public.state_species
  for select to anon, authenticated using (true);
drop policy if exists state_species_admin_all on public.state_species;
create policy state_species_admin_all on public.state_species
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Populate (idempotent) --
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'deer'
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'elk' and st.code in ('AZ','CA','CO','ID','MT','NV','NM','OR','UT','WA','WY','KS','MN','NE','ND','OK','SD','AR','KY','MI','PA','TN','VA','WI','WV')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'moose' and st.code in ('AK','CO','ID','ME','MT','ND','NH','UT','VT','WA','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'pronghorn' and st.code in ('AZ','CA','CO','ID','KS','MT','NE','NV','NM','ND','OK','OR','SD','TX','UT','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'caribou' and st.code in ('AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'bison' and st.code in ('AK','AZ','MT','SD','UT','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'bighorn-sheep' and st.code in ('AZ','CA','CO','ID','MT','NE','NV','NM','ND','OR','SD','TX','UT','WA','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'dall-sheep' and st.code in ('AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'mountain-goat' and st.code in ('AK','CO','ID','MT','NV','OR','UT','WA','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'muskox' and st.code in ('AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'bear' and st.code in ('AK','AZ','AR','CA','CO','GA','ID','ME','MD','MA','MI','MN','MT','NH','NJ','NM','NY','NC','OR','PA','TN','UT','VT','VA','WA','WV','WI','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'brown-bear' and st.code in ('AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'mountain-lion' and st.code in ('AZ','CO','ID','MT','NE','NV','NM','ND','OR','SD','TX','UT','WA','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'javelina' and st.code in ('AZ','NM','TX')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'wild-hog' and st.code in ('AL','AR','CA','FL','GA','HI','KY','LA','MS','NC','OK','SC','TN','TX','VA','WV')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'turkey' and st.code not in ('AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'duck'
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'goose'
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'dove' and st.code not in ('MI','NY','NJ','ME','VT','NH','MA','CT','AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'band-tailed-pigeon' and st.code in ('AZ','CA','CO','NM','OR','WA','UT')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'sandhill-crane' and st.code in ('AL','AK','AZ','CO','ID','KS','KY','MN','MT','NM','ND','OK','SD','TN','TX','UT','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'woodcock' and st.code in ('AL','AR','CT','DE','FL','GA','IL','IN','IA','KY','LA','ME','MD','MA','MI','MN','MS','MO','NH','NJ','NY','NC','OH','PA','RI','SC','TN','VT','VA','WV','WI')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'snipe' and st.code not in ('HI')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'pheasant' and st.code in ('SD','ND','KS','NE','IA','MN','MT','CO','WI','IL','MI','IN','MO','WY','WA','OR','ID','CA','UT','NV','TX','OK','NM','AZ','OH','PA','NY','NJ','MD','DE','MA','CT','RI','SC','VA','KY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'bobwhite' and st.code in ('TX','OK','KS','AL','GA','FL','MS','LA','AR','SC','NC','TN','MO','NE','IA','KY','VA','WV','IL','IN','CO','OH','WI','NY','PA','NJ','MD')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'western-quail' and st.code in ('AZ','NM','TX','CA','NV','UT','OR','WA','ID','CO','OK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'ruffed-grouse' and st.code in ('ME','NH','VT','MA','CT','RI','NY','PA','MD','WV','VA','NC','GA','OH','MI','WI','MN','IA','MT','ID','WY','UT','WA','OR','AK','ND','SD','TN','KY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'spruce-grouse' and st.code in ('AK','MN','MT','ID','WA','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'sharptail-grouse' and st.code in ('ND','SD','MT','WY','ID','NE','CO','UT','MN','MI','AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'sage-grouse' and st.code in ('MT','WY','ID','NV','OR','UT','CO')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'prairie-chicken' and st.code in ('KS','NE','SD','CO','MN','OK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'chukar' and st.code in ('AZ','CA','CO','ID','MT','NV','OR','UT','WA','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'gray-partridge' and st.code in ('IA','ID','MN','MT','ND','NE','NV','OR','SD','UT','WA','WI','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'ptarmigan' and st.code in ('AK','CO','UT')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'rabbit' and st.code not in ('AK','HI')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'snowshoe-hare' and st.code in ('ME','NH','VT','MA','NY','PA','MI','WI','MN','MT','ID','WY','CO','UT','WA','OR','AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'squirrel' and st.code not in ('AK','HI')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'coyote' and st.code not in ('HI')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'bobcat' and st.code not in ('OH','NJ','DE','HI')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'fox' and st.code not in ('HI','AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'raccoon' and st.code not in ('HI','AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'fisher' and st.code in ('ME','NH','VT','MA','CT','RI','NY','PA','WV','MI','WI','MN')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'marten' and st.code in ('ME','NY','MN','MT','ID','WY','CO','UT','NV','OR','WA','AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'nutria' and st.code in ('LA','TX','OR','WA','MS','AL','GA','FL','SC','NC','VA')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'ringtail' and st.code in ('AZ','NM','TX','NV','UT')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'wolf' and st.code in ('AK','ID','MT','WY')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'wolverine' and st.code in ('AK')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'alligator' and st.code in ('AL','AR','FL','GA','LA','MS','SC','TX')
  on conflict do nothing;
insert into public.state_species (state_id, species_id)
  select st.id, sp.id from public.states st, public.species sp
  where sp.key = 'crow' and st.code not in ('HI')
  on conflict do nothing;
